# 'study_prefix' should be a string at the start of each table. We'll use this
# to clean up queries, so it should be unique. Name your tables in the following
# format: [study_prefix]__[table_name]. It should probably, but not necessarily,
# be the same name as the folder the study definition is in.
study_prefix = "glioma"


# The following section describes all tables that should be generated directly
# from SQL files.

[file_config.file_names]
"Glioma valuesets" = [
    "athena/glioma__valueset_topography.sql",
]
"Glioma inclusion criteria for study population" = [
    "athena/glioma__include_gender.sql",
    "athena/glioma__include_age_at_visit.sql",
    "athena/glioma__include_utilization.sql",
    "athena/glioma__include_study_period.sql",
]
"Glioma study period" = [
    "athena/glioma__cohort_study_period.sql",
]
"Glioma study population" = [
    "athena/glioma__cohort_study_population.sql",
]
"Glioma study population (dx, rx, lab, doc, diag)" = [
    "athena/glioma__cohort_study_population_dx.sql",
    "athena/glioma__cohort_study_population_rx.sql",
    "athena/glioma__cohort_study_population_lab.sql",
    "athena/glioma__cohort_study_population_doc.sql",
    "athena/glioma__cohort_study_population_diag.sql",
    "athena/glioma__cohort_study_population_proc.sql",
]
"Glioma cohorts (dx, rx, doc, diag)" = [
    "athena/glioma__cohort_casedef.sql",
    "athena/glioma__cohort_rx.sql"
]
"Glioma include (dx before rx)" = [
    "athena/glioma__cohort_include.sql"
]
"Glioma powerset patient counts" = [
    "athena/glioma__count_encounter_lab.sql",
    "athena/glioma__count_patient_lab.sql",
]

#[export_config]

