# 'study_prefix' should be a string at the start of each table. We'll use this
# to clean up queries, so it should be unique. Name your tables in the following
# format: [study_prefix]__[table_name]. It should probably, but not necessarily,
# be the same name as the folder the study definition is in.
study_prefix = "glioma"


# The following section describes all tables that should be generated directly
# from SQL files.

[file_config.file_names]
"valuesets" = [
    "athena/glioma__valueset_casedef.sql",
    "athena/glioma__valueset_morphology.sql",
]
"inclusion criteria for study population" = [
    "athena/glioma__include_gender.sql",
    "athena/glioma__include_age_at_visit.sql",
    "athena/glioma__include_utilization.sql",
    "athena/glioma__include_study_period.sql",
]
"study period" = [
    "athena/glioma__cohort_study_period.sql",
]
"study population" = [
    "athena/glioma__cohort_study_population.sql",
]
"study population (dx, rx, lab, doc, diag)" = [
    "athena/glioma__cohort_study_population_dx.sql",
    "athena/glioma__cohort_study_population_rx.sql",
    "athena/glioma__cohort_study_population_lab.sql",
    "athena/glioma__cohort_study_population_doc.sql",
    "athena/glioma__cohort_study_population_diag.sql",
    "athena/glioma__cohort_study_population_proc.sql",
]
"COHORT matching glioma case definition" = [
    "athena/glioma__cohort_casedef.sql",
]
"COHORT glioma case definition (pre, index, index_post, post)" = [
    "athena/glioma__cohort_casedef_pre.sql",
    "athena/glioma__cohort_casedef_index.sql",
    "athena/glioma__cohort_casedef_index_post.sql",
    "athena/glioma__cohort_casedef_post.sql",
]
"SAMPLE glioma case definition (pre, index, index_post, post)" = [
    "athena/glioma__sample_casedef_pre.sql",
    "athena/glioma__sample_casedef_index.sql",
    "athena/glioma__sample_casedef_index_post.sql",
    "athena/glioma__sample_casedef_post.sql",
]
"COMORBIDITIES of glioma cohort" = [
    "athena/glioma__cohort_casedef_comorbidity.sql",
]
"cube counts" = [
    "athena/glioma__cube_patient_casedef.sql",
    "athena/glioma__cube_encounter_casedef.sql",
]

#[export_config]

